### ISSUE TITLE
I'm getting Errors while using your project 

### ISSUE THREAD

**Issue by Davronjuraev** [Zakarialabib/marketplace-app#1]
Hello, Sir.
Thank you for your sharing this good job.
I've some problem,  Like this:
View [admin.product.edit] not found.
and many others, i think you have updated now.
Please share us with updated and resolved some problems.
Thank you very much

**Comment by Zakarialabib** [comment]
Hi, please desribe in details, or send pr with changes

**Comment by Davronjuraev** [comment]
for example if i go to admin panel, for creating new product getting this one 
![image](https://github.com/Zakarialabib/Laravel-ecommerce-marketplace/assets/15152078/f5e1c6cd-3ac2-41e2-afa5-aa50539d1791)

**Comment by Zakarialabib** [comment]
Check Laravel Ecommerce,
https://github.com/Zakarialabib/Laravel-Ecommerce
 this project is deprecated
